bar-chart-horizontal-sm/script.js
bar-chart-horizontal-with-dropdown/script.js
bar-chart-horizontal/script.js
grouped-bar-chart/script.js

Applying the same fix to four charts that use the same code:
- Grouped bar chart
- Bar chart horizontal
- Bar chart horizontal with dropdown
- Bar chart horizontal small multiple

Applying fix to "auto" x-domain calculations

---

bar-chart-horizontal-grouped-clustered/chart.css
bar-chart-horizontal-grouped-clustered/config.js
bar-chart-horizontal-grouped-clustered/data.csv
bar-chart-horizontal-grouped-clustered/index.html
bar-chart-horizontal-grouped-clustered/script.js

Grouped, clustered horizontal bar chart

Adding new chart template

---

bar-chart-horizontal-grouped/chart.css
bar-chart-horizontal-grouped/config.js
bar-chart-horizontal-grouped/data.csv
bar-chart-horizontal-grouped/index.html
bar-chart-horizontal-grouped/script.js

Adding Peter B's bar-chart-horizontal-grouped

Adding new chart: bar-chart-horizontal-grouped

---

area-stacked-sm/script.js
bar-chart-horizontal-stacked-sm/script.js

Fixed the issue with pym not sending the correct chart height.

Micheal slade/issue80

---

ridgeline-plot/script.js

Micheal is a dumb dumb...sorry

Ridge-plot-fix-ms

---

line-chart-sm/config.js
line-chart-sm/script.js
line-chart/config.js
line-chart/script.js

For line chart and small multiple line chart:
X-axis label is now y-axis label
The "auto" domain calculation now works
Added zero-line

Small multiple line fixes

---

column-chart-stacked-sm/chart.css
column-chart-stacked-sm/config.js
column-chart-stacked-sm/script.js
column-chart-stacked/chart.css
column-chart-stacked/config.js
column-chart-stacked/script.js

Grid layout
Order of legend matches stack order of bars

Improving stacked column legends

---

bar-chart-horizontal-with-reference-sm/chart.css
bar-chart-horizontal-with-reference-sm/script.js

Adding a legend for the horizontal bar with reference line chart

Bar with reference legend

---

line-chart-with-area/config.js
line-chart-with-area/script.js
scatter-plot/config.js
scatter-plot/script.js

Line chart with area and scatterplot

Code fixes

---

scatter-plot/config.js
scatter-plot/script.js

wrap x axis label

---

column-chart-sm/config.js
column-chart-sm/script.js
column-chart-stacked-sm/config.js
column-chart-stacked-sm/script.js
column-chart-stacked-with-line-sm/config.js
column-chart-stacked-with-line-sm/script.js
column-chart-stacked-with-line/config.js
column-chart-stacked-with-line/script.js
column-chart-stacked/config.js
column-chart-stacked/script.js
column-chart/config.js
column-chart/script.js

Not sure how useful this is now(!) but adjusting the column chart templates to be able to interpret numeric data on the x-axis

Allowing for numeric x-axis values

---

line-chart-sm/config.js
line-chart-sm/script.js

Just copied some code from a column chart

Added xAxis Label to sm line template

---

area-stacked-sm/config.js
area-stacked-sm/script.js
area-stacked/config.js
area-stacked/script.js

Allowing stack offset and stack order options
Adding y-axis label to area chart

Updating area charts

---

area-stacked-sm/script.js
bar-chart-horizontal-stacked-sm/script.js

Fixing a bug I introduced on these templates

Fixing area and stacked bar sm charts

---

bar-chart-horizontal-with-dropdown/data.csv
bar-chart-horizontal-with-dropdown/script.js

Template wasn't able to handle negative values and now it can.

Fixed the dropdown bars so it can handle negative values

---

area-stacked-sm/chart.css
bar-chart-horizontal-grouped-clustered/chart.css
bar-chart-horizontal-grouped/chart.css
bar-chart-horizontal-stacked-clustered-grouped/chart.css
bar-chart-horizontal-stacked-clustered/chart.css
bar-chart-horizontal-stacked-grouped/chart.css
comet-clustered/chart.css
comet-plot/chart.css
lib/globalStyle.css
line-chart-sm-colours/chart.css
line-chart-sm/chart.css
line-chart-with-ci-sm/chart.css
range-plot/chart.css

Also, tidied up some duplicate css on small multiple titles

Removed extra margin on grouped charts and moved to globalStyle

---

dot-plot/chart.css
dot-plot/config.js
dot-plot/script.js
range-plot/chart.css
range-plot/config.js
range-plot/script.js
schema.JSON

Update range/dot plot with alternative shape for accessibility (diamond)

---

range-plot-sm/chart.css
range-plot-sm/config.js
range-plot-sm/data.csv
range-plot-sm/index.html
range-plot-sm/script.js

Small multiple range plot - initial commit. From DVC 2883 figure 7. Uses Mike's utility functions
Fixes #236

Small multiple range plot - initial commit.

---

chart-menu/chartConfig.js
chart-menu/index.html
chart-menu/script.js

Everyone to do with the charts in one place.

Restructure chart menu so runs off one json

---

column-chart-clustered/chart.css
column-chart-clustered/config.js
column-chart-clustered/data.csv
column-chart-clustered/index.html
column-chart-clustered/script.js
lib/helpers.js

Was created for Sam W's work on first time buyers, it's not perfect, it's also only really set up to work with categories not dates (basically just a bar chart on it's side) so it's quite niche, but I'm sure it could be adapted quite easily.

Added a clustered column chart template

---

heatmap/config.js
heatmap/script.js

Some simple fixes for the heatmap

allows custom colours, fixes equal breaks, improves text contrast handling for heatmap

---

line-chart-dropdown-options/config.js
line-chart-dropdown-options/script.js
line-chart/config.js
line-chart/script.js

feat: Separate and rationalise min/max values and y axis auto calculation for line charts (also returns line-chart-dropdown y axis gridlines)

Improving the y-axis configuration for line chart and line-chart-dropdown
